### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by skleung** [skleung/Community#11]
Last thing to tackle before going public!

Ability to factor diners into **groups**
- Each group has a group ID that you can join. (Group ID and a password)
- If you're not signed into a group: you can either join or create a group.
- Group creator has adding capabilities and password changing capabilities, but no one else does (this role is different from admin)
- A diner can be in multiple groups but then you can tab between groups

**Comment by skleung** [comment]
See @Kevin's issue

**Comment by kacasey8** [comment]
done
