### ISSUE TITLE
Testing environment

### ISSUE THREAD

**Issue by skleung** [skleung/Community#12]
I'm envisioning some sort of testing environment that we can give people to try out and demo the product. This can be approached in two ways:
1. **community-food.herokuapp.com:** We take advantage of @Fortisque dupe of the product and allow people to log in, make groups.
2. **test-group:** We let people login to a testing group that doesn't actually process any payments...we'll have to be careful to basically deny everyone the ability of making venmo payments if their group id is the same as the test-group's.

**Comment by kacasey8** [comment]
Using option 2.  Handled by 812d42473aa515dc1692b7b5183be8bc5b6f421b and 9e28d0fa5f370144b35c336cf39e488a05c2b631 and heroku config
