### ISSUE TITLE
automatically enter in the date when popping up a modal from the calendar

### ISSUE THREAD

**Issue by skleung** [skleung/Community#15]
probably needs some restyles too

**Comment by kacasey8** [comment]
can we use jquery datepicker instead of the rails f.dateselect?  Think it would be pretty easy

**Comment by skleung** [comment]
Yeah. Thing is we need to pass in the date with javascript so that the date
box is automatically filled.

**Comment by kacasey8** [comment]
This should be fixed with @67587130655d959ba5415a86a9ff184649344fc6
