### ISSUE TITLE
Asplode..while trying to find jquery? 

### ISSUE THREAD

**Issue by skleung** [skleung/Community#19]
I'll look more into this
![screen shot 2014-07-23 at 11 11 27 pm](https://cloud.githubusercontent.com/assets/3238124/3684317/7076e7c6-12f9-11e4-8d77-dc128289dda2.png)

**Comment by kacasey8** [comment]
did u bundle install? i added the jquery ui gem

**Comment by skleung** [comment]
I did bundle install and update, but no cookie.

Hm. Well, I'll show you tomorrow.

**Comment by kacasey8** [comment]
synced jquery-ui gem version to 5.0.0 and used require jquery-ui
