### ISSUE TITLE
Password Reset Broken

### ISSUE THREAD

**Issue by skleung** [skleung/Community#20]
As my friends have been asking for a password reset - it would be nice if the password reset didn't cause a 500 error. I've been trying to replicate on local, but haven't been able to launch the app.

**Comment by skleung** [comment]
Do we need to work on a mailer model so we can send password reset emails?

**Comment by kacasey8** [comment]
should be fixed with @377fe1a3d63b84e94b9c36f766d30eca8989626d  
use heroku config:set GMAIL_DOMAIN=gmail.com GMAIL_USERNAME=gmailusername GMAIL_PASSWORD=gmailpassword

We should create a custom gmail for this maybe
