### ISSUE TITLE
Dissapearing Ingredients from Meals

### ISSUE THREAD

**Issue by skleung** [skleung/Community#26]
Reproduce by making a new meal, adding people/ingredients so that they appear as rows on your dashboard.
Then edit the meal by removing an ingredient. You should see two things:
1. The balance between diners on the dashboard looks empty, but you should still owe them something
2. Upon further investigation, it looks like you're getting NaN when calling request_amount_from. This is further confirmed when ingredient.servings returns 0 (probably a divide by 0 error)

I'm not sure if the DinersMeals is getting correctly updated when we edit and save a meal?

**Comment by kacasey8** [comment]
should be fixed 45a1a6603cf4637e41321f2692275b45d657872b
