### ISSUE TITLE
Updating meal with modal doesn't show flash and redirect

### ISSUE THREAD

**Issue by skleung** [skleung/Community#35]
My friend reported that upon updating a meal the changes got saved but it kept her on the same edit meal page without redirecting back to the list of meals or the updated meal.

Ive tried using format.html and a straight up redirect-to but it seems like its getting blocked by the fact we're using a modal?

**Comment by kacasey8** [comment]
eh my bad, I'm using format.js b/c the request is ajax now.  I thought the redirect_to would work so i never bothered testing it, i'll get a fix in a few minutes

**Comment by skleung** [comment]
No worries, there's no real rush. I just wanted to document it before I
forget.

I think once I address the other issue with auto adding someone to a meal
in the test group,  we can push the app out to more people.
On Aug 20, 2014 2:26 PM, "Kevin Casey" notifications@github.com wrote:

eh my bad, I'm using format.js b/c the request is ajax now. I thought the
redirect_to would work so i never bothered testing it, i'll get a fix in a
few minutes
